### ISSUE TITLE
Lab file asks for separate display of ships, but test fails if you do that. 

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/sinatra-nested-forms#19]
I have 3 example files for "show.erb". 

The one currently named 'show.erb' (in pirates folder) passes the tests. 

The other examples 'show1.erb' and 'show2.erb' show the 2 separate ships as the lab file asks for in labels "Display your first ships here" and "Display your 2nd ship here". 

However, if you do that, the rspec test fails because it can't find "Flying Dutchman".  

Please let me know if there is a way to display the 2 ships data in specific areas of the show.erb file and still pass the test.   I looked at github for other student's code and did not see anyone meeting this 'requirement'.    So I passed the tests and will keep moving, but want to raise the question.     THANKS  -Brad Smith

**Comment by AnnJohn** [comment]
hi @mendelB; i'm reassigning this one to @pletcher if that works for you.

**Comment by pletcher** [comment]
It wasn't the views per se, it was that ships weren't being cleared out from previous tests.
