### ISSUE TITLE
no biggie, just a line left out of building hash with Ruby

### ISSUE THREAD

**Issue by stazman** [learn-co-curriculum/sinatra-nested-forms#23]
It looks like my_hash["student"]["grade"] = "9" should be under my_hash["student"]["name"] = "Joe".

Also, my_hash => {"student"=> {"name" = "Joe", "course"=>{"name"=>"US History", "topic"=>"History"}}} should be my_hash => {"student"=> {"name" = "Joe", "grade" = "9", course"=>{"name"=>"US History", "topic"=>"History"}}}.

Cheers

**Comment by curiositypaths** [comment]
Hi there,

Any chance this issue is related to another repository? This lesson deals with `pirates` and `ships`.

As always thank you for contributing!

**Comment by stazman** [comment]
whoops, sorry! Thanks for the email!


Christopher DiStasio

(334) 759-9051
Have a good day!
