### ISSUE TITLE
A little confused.

### ISSUE THREAD

**Issue by FionaDL** [learn-co-curriculum/sinatra-nested-forms#24]
I was slightly confused by the difference between the Learn page instructions and the instructions that are within the root.erb. Is this done on purpose? I had a lot of trouble understanding exactly what the lab was wanting me to do.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
