### ISSUE TITLE
Root.erb text differs 

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/sinatra-nested-forms#26]
Hey there,

There is text in the root.erb file, but in order to get it to pass, students are required to add text that is not anywhere except the solution file. This isn't something you can figure out without looking at the solution. I would just copy the text from the solution into the root.erb file and omit the test for it.

**Comment by maxwellbenton** [comment]
Hi @helloamandamurphy,

Thank you for opening this issue and providing feedback. We've updated the tests for this lab to no longer look for the specific instructions content, made sure the text in root.erb is in both master and solution, and believe this issue has been resolved. 

Thank you again for bringing this and all of the issues you have opened to our attention!
